
import StickDiagram
import DesignParameters
import DRC

import ViaPoly2Met1_resize
import SupplyRails
import CascodeNMOS
import CascodePMOS


class TristateInverterF1(StickDiagram._StickDiagram):
    _ParametersForDesignCalculation = dict(NMOSWidth=None,
                                              PMOSWidth=None,
                                              ChannelLength=None,
                                              XVT=None,
                                              GateSpacing=None,

                                              CellHeight=None,
                                              VDD2PMOS=None,
                                              VSS2NMOS=None,
                                           )

    def __init__(self, _DesignParameter=None, _Name='TristateInverter'):
        if _DesignParameter != None:
            self._DesignParameter = _DesignParameter
        else:
            self._DesignParameter = dict(
                _Name=self._NameDeclaration(_Name=_Name), _GDSFile=self._GDSObjDeclaration(_GDSFile=None)
            )

    def _CalculateDesignParameter(self,
                                  NMOSWidth=None,
                                  PMOSWidth=None,
                                  ChannelLength=None,
                                  XVT=None,
                                  GateSpacing=None,

                                  CellHeight=None,
                                  VDD2PMOS=None,
                                  VSS2NMOS=None,
                                  ):
        drc = DRC.DRC()
        _Name = self._DesignParameter['_Name']['_Name']


        self._DesignParameter['InputVia_EN'] = self._SrefElementDeclaration(_DesignObj=ViaPoly2Met1_resize._ViaPoly2Met1_resize(_Name='InputVia_ENIn{}'.format(_Name)))[0]
        self._DesignParameter['InputVia_EN']['_DesignObj']._CalculateDesignParameter(**dict(_ViaPoly2Met1NumberOfCOX=1, _ViaPoly2Met1NumberOfCOY=2, Met1XWidth=66, Met1YWidth=200, POXWidth=40, POYWidth=200))
        self._DesignParameter['InputVia_EN']['_XYCoordinates'] = [[(- 130.0), 725.0]]
        self._DesignParameter['InputVia_A'] = self._SrefElementDeclaration(_DesignObj=ViaPoly2Met1_resize._ViaPoly2Met1_resize(_Name='InputVia_AIn{}'.format(_Name)))[0]
        self._DesignParameter['InputVia_A']['_DesignObj']._CalculateDesignParameter(**dict(_ViaPoly2Met1NumberOfCOX=1, _ViaPoly2Met1NumberOfCOY=2, Met1XWidth=66, Met1YWidth=200, POXWidth=40, POYWidth=200))
        self._DesignParameter['InputVia_A']['_XYCoordinates'] = [[130.0, 900.0]]
        self._DesignParameter['InputVia_ENb'] = self._SrefElementDeclaration(_DesignObj=ViaPoly2Met1_resize._ViaPoly2Met1_resize(_Name='InputVia_ENbIn{}'.format(_Name)))[0]
        self._DesignParameter['InputVia_ENb']['_DesignObj']._CalculateDesignParameter(**dict(_ViaPoly2Met1NumberOfCOX=1, _ViaPoly2Met1NumberOfCOY=2, Met1XWidth=66, Met1YWidth=200, POXWidth=40, POYWidth=200))
        self._DesignParameter['InputVia_ENb']['_XYCoordinates'] = [[(- 130.0), 1050.0]]
        self._DesignParameter['VSSRail'] = self._SrefElementDeclaration(_DesignObj=SupplyRails.SupplyRail(_Name='VSSRailIn{}'.format(_Name)))[0]
        self._DesignParameter['VSSRail']['_DesignObj']._CalculateDesignParameter(**dict(NumPitch=3, UnitPitch=(GateSpacing + ChannelLength), Met1YWidth=80, Met2YWidth=300, PpNpYWidth=180, isPbody=True))
        self._DesignParameter['VSSRail']['_XYCoordinates'] = [[0.0, 0.0]]
        self._DesignParameter['VDDRail'] = self._SrefElementDeclaration(_DesignObj=SupplyRails.SupplyRail(_Name='VDDRailIn{}'.format(_Name)))[0]
        self._DesignParameter['VDDRail']['_DesignObj']._CalculateDesignParameter(**dict(NumPitch=3, UnitPitch=(GateSpacing + ChannelLength), Met1YWidth=80, Met2YWidth=300, PpNpYWidth=180, isPbody=False))
        self._DesignParameter['VDDRail']['_XYCoordinates'] = [[0, CellHeight]]
        self._DesignParameter['CascodeNMOS'] = self._SrefElementDeclaration(_DesignObj=CascodeNMOS._CascodeNMOS(_Name='CascodeNMOSIn{}'.format(_Name)))[0]
        self._DesignParameter['CascodeNMOS']['_DesignObj']._CalculateDesignParameter(**dict(_NMOSChannelWidth=NMOSWidth, _NMOSChannellength=ChannelLength, _NMOSDummy=True, _XVT=XVT, _GateSpacing=GateSpacing))
        self._DesignParameter['CascodeNMOS']['_XYCoordinates'] = [[0, VSS2NMOS]]
        self._DesignParameter['CascodePMOS'] = self._SrefElementDeclaration(_DesignObj=CascodePMOS._CascodePMOS(_Name='CascodePMOSIn{}'.format(_Name)))[0]
        self._DesignParameter['CascodePMOS']['_DesignObj']._CalculateDesignParameter(**dict(_PMOSChannelWidth=PMOSWidth, _PMOSChannellength=ChannelLength, _PMOSDummy=True, _XVT=XVT, _GateSpacing=GateSpacing))
        self._DesignParameter['CascodePMOS']['_XYCoordinates'] = [[0, (CellHeight - VDD2PMOS)]]
        self._DesignParameter['VSSRouting'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _XWidth=self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'], _YWidth=(((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - ((self._DesignParameter['VSSRail']['_XYCoordinates'][0][1] + self._DesignParameter['VSSRail']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['VSSRail']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))))
        self._DesignParameter['VSSRouting']['_XYCoordinates'] = [[(self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][1][0]), ((((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + ((self._DesignParameter['VSSRail']['_XYCoordinates'][0][1] + self._DesignParameter['VSSRail']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['VSSRail']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['VDDRouting'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _XWidth=self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'], _YWidth=(((self._DesignParameter['VDDRail']['_XYCoordinates'][0][1] + self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - ((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))))
        self._DesignParameter['VDDRouting']['_XYCoordinates'] = [[(self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][1][0]), ((((self._DesignParameter['VDDRail']['_XYCoordinates'][0][1] + self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + ((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['POLY_boundary_30'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=ChannelLength, _YWidth=(((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - ((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))))
        self._DesignParameter['POLY_boundary_30']['_XYCoordinates'] = [[(self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]), ((((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + ((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['POLY_boundary_29'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=(((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) - ((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))), _YWidth=((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][0][1]) - ((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))))
        self._DesignParameter['POLY_boundary_29']['_XYCoordinates'] = [[((((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) + ((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))) / 2), (((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][0][1]) + ((self._DesignParameter['InputVia_EN']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_EN']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['POLY_boundary_24'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=ChannelLength, _YWidth=(((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - ((self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))))
        self._DesignParameter['POLY_boundary_24']['_XYCoordinates'] = [[(self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]), ((((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + ((self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['POLY_boundary_23'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=(((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) - ((self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))), _YWidth=(((self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - (self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][1][1])))
        self._DesignParameter['POLY_boundary_23']['_XYCoordinates'] = [[((((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) + ((self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))) / 2), ((((self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + (self._DesignParameter['InputVia_ENb']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_ENb']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][1][1])) / 2)]]
        self._DesignParameter['POLY_boundary_28'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=ChannelLength, _YWidth=(((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - ((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))))
        self._DesignParameter['POLY_boundary_28']['_XYCoordinates'] = [[(self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][0]), ((((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + ((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['POLY_boundary_21'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=ChannelLength, _YWidth=(((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - ((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))))
        self._DesignParameter['POLY_boundary_21']['_XYCoordinates'] = [[(self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][0]), ((((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + ((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['POLY_boundary_27'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=(((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) - ((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][0]) - (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))), _YWidth=((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][0][1]) - ((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))))
        self._DesignParameter['POLY_boundary_27']['_XYCoordinates'] = [[((((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) + ((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][0]) - (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))) / 2), (((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][0][1]) + ((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['POLY_boundary_25'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=(((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) - ((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][0]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))), _YWidth=(((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - (self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][1][1])))
        self._DesignParameter['POLY_boundary_25']['_XYCoordinates'] = [[((((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][0] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) + ((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][1][0]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))) / 2), ((((self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + (self._DesignParameter['InputVia_A']['_XYCoordinates'][0][1] + self._DesignParameter['InputVia_A']['_DesignObj']._DesignParameter['_COLayer']['_XYCoordinates'][1][1])) / 2)]]
        self._DesignParameter['NWELL_boundary_2'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['NWELL'][0], _Datatype=DesignParameters._LayerMapping['NWELL'][1], _XWidth=max((self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_ODLayer']['_XWidth'] + (2 * drc._NwMinEnclosurePactive2)), (self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_ODLayer']['_XWidth'] + (2 * drc._NwMinEnclosurePactive))), _YWidth=((((self._DesignParameter['VDDRail']['_XYCoordinates'][0][1] + self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2)) - ((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2))) + (2 * drc._NwMinEnclosurePactive)))
        self._DesignParameter['NWELL_boundary_2']['_XYCoordinates'] = [[0, ((((self._DesignParameter['VDDRail']['_XYCoordinates'][0][1] + self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['VDDRail']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2)) + ((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2))) / 2)]]
        self._DesignParameter['OutputRouting'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'])
        self._DesignParameter['OutputRouting']['_XYCoordinates'] = [[[((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) + (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), (((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))], [(self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_PPLayer']['_XYCoordinates'][0][0]), (((self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))], [(self._DesignParameter['CascodePMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_PPLayer']['_XYCoordinates'][0][0]), (((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))], [((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][0] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), (((self._DesignParameter['CascodeNMOS']['_XYCoordinates'][0][1] + self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['CascodeNMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - (self._DesignParameter['CascodePMOS']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))]]]







if __name__ == '__main__':

    from Private import MyInfo
    import DRCchecker

    libname = 'TristateInverterF1_x3'
    cellname = 'TristateInverterF1_x3'
    _fileName = cellname + '.gds'

    ''' Input Parameters for Layout Object '''
    InputParams = dict(

        NMOSWidth=300,
        PMOSWidth=600,
        ChannelLength=30,
        XVT='SLVT',
        GateSpacing=100,

        CellHeight=2100,
        VDD2PMOS=500,
        VSS2NMOS=300,
    )

    ''' Generate Layout Object '''
    LayoutObj = TristateInverterF1(_DesignParameter=None, _Name=cellname)
    LayoutObj._CalculateDesignParameter(**InputParams)
    LayoutObj._UpdateDesignParameter2GDSStructure(_DesignParameterInDictionary=LayoutObj._DesignParameter)
    testStreamFile = open('./{}'.format(_fileName), 'wb')
    tmp = LayoutObj._CreateGDSStream(LayoutObj._DesignParameter['_GDSFile']['_GDSFile'])
    tmp.write_binary_gds_stream(testStreamFile)
    testStreamFile.close()

    print('###############      Sending to FTP Server...      ##################')
    My = MyInfo.USER(DesignParameters._Technology)
    Checker = DRCchecker.DRCchecker(
        username=My.ID,
        password=My.PW,
        WorkDir=My.Dir_Work,
        DRCrunDir=My.Dir_DRCrun,
        libname=libname,
        cellname=cellname,
        GDSDir=My.Dir_GDS
    )
    Checker.Upload2FTP()
    Checker.StreamIn(tech=DesignParameters._Technology)

    print('#############################      Finished      ################################')
    # end of 'main():' ---------------------------------------------------------------------------------------------
